# Generated by Django 3.2 on 2021-06-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stucollage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stupass',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stustate',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='no data', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='no data', max_length=40),
        ),
    ]
