# Generated by Django 3.2 on 2021-06-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_rename_email_student_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
