# Generated by Django 3.2 on 2021-06-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('collage', models.CharField(max_length=40)),
            ],
        ),
    ]
